name: Python uppercase
# python
on:
  push: 
    paths:
      - "py-upper/**"
      - ".github/workflows/python-uppercase.yml"
      - ".github/workflows/python-uppercase.yaml"
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check python version
        run: python -V
      - name: Download application code
        uses: actions/checkout@v4
